#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class LittleElephantAndBalls {
public:
	int getNumber(string S)
	{
	    set<char> left, right;
	    int res = 0;
        for(int i=0;i<S.size();i++)
        {
            res = res + left.size() + right.size();
            if(left.count(S[i]))
                right.insert(S[i]);
            else
                left.insert(S[i]);
        }
        return res;

	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, string p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << "\"" << p0 << "\"";
	cout << "]" << endl;
	LittleElephantAndBalls *obj;
	int answer;
	obj = new LittleElephantAndBalls();
	clock_t startTime = clock();
	answer = obj->getNumber(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	string p0;
	int p1;

	{
	// ----- test 0 -----
	p0 = "RGB";
	p1 = 3;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 1 -----
	p0 = "RGGRBBB";
	p1 = 21;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 2 -----
	p0 = "RRRGBRR";
	p1 = 16;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 3 -----
	p0 = "RRRR";
	p1 = 5;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 4 -----
	p0 = "GGRRRGR";
	p1 = 18;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 5 -----
	p0 = "G";
	p1 = 0;
	all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
	// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
//
// Little Elephant from the Zoo of Lviv likes balls.
// He has some balls that he wants to arrange into a row on the table.
// Each of those balls has one of three possible colors: red, green, or blue.
//
//
//
//
// You are given a string S.
// This string represents all of the balls Little Elephant has, in the order in which he will be placing them onto the table.
// Red, green, and blue balls are represented by the characters 'R', 'G', and 'B', respectively.
// Each time Little Elephant places a new ball onto the table, he may add it anywhere into the row of already placed balls.
//
//
//
//
// Additionally, each time Little Elephant adds a ball to the table, he scores some points (possibly zero).
// The number of points is calculated as follows:
//
// If this is the first ball being placed on the table, there are 0 points for it.
// If he adds the current ball to one of the ends of the row, the number of points scored is equal to the number of different colors of the balls on the table, excluding the current ball.
// If he adds the current ball between two other balls, the number of points scored is equal to the number of different colors of the balls before the current ball, plus the number of different colors of the balls after the current ball.
//
//
//
//
//
// For example, suppose that the balls currently on the table form the row "GBBG".
// Little Elephant now wants to add a new red ball ('R').
// One of the options is to add it to the beginning.
// This scores 2 points and produces the row "RGBBG".
// Another option is to add it between "GBB" and "G".
// There are 2 distinct colors in "GBB" and 1 in "G", so this move is worth 2+1 = 3 points.
// This move produces the row "GBBRG".
//
//
//
//
// Return the maximum total number of points that Little Elephant can earn for placing the balls onto the table.
//
//
// DEFINITION
// Class:LittleElephantAndBalls
// Method:getNumber
// Parameters:string
// Returns:int
// Method signature:int getNumber(string S)
//
//
// CONSTRAINTS
// -S will contain between 1 and 50 characters, inclusive.
// -S will consist only of characters 'R', 'G' and 'B'.
//
//
// EXAMPLES
//
// 0)
// "RGB"
//
// Returns: 3
//
// Any strategy is optimal here. Each strategy scores 0+1+2 = 3 points.
//
// 1)
// "RGGRBBB"
//
// Returns: 21
//
//
//
// 2)
// "RRRGBRR"
//
// Returns: 16
//
//
//
// 3)
// "RRRR"
//
// Returns: 5
//
//
//
// 4)
// "GGRRRGR"
//
// Returns: 18
//
//
//
// 5)
// "G"
//
// Returns: 0
//
//
//
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
