#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class MiningGoldEasy {
public:
	int GetMaximumGold(int N, int M, vector <int> event_i, vector <int> event_j) {
		
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, int p1, vector <int> p2, vector <int> p3, bool hasAnswer, int p4) {
	cout << "Test " << testNum << ": [" << p0 << "," << p1 << "," << "{";
	for (int i = 0; int(p2.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p2[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p3.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p3[i];
	}
	cout << "}";
	cout << "]" << endl;
	MiningGoldEasy *obj;
	int answer;
	obj = new MiningGoldEasy();
	clock_t startTime = clock();
	answer = obj->GetMaximumGold(p0, p1, p2, p3);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p4 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p4;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	int p0;
	int p1;
	vector <int> p2;
	vector <int> p3;
	int p4;
	
	{
	// ----- test 0 -----
	p0 = 2;
	p1 = 2;
	int t2[] = {0};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	int t3[] = {0};
			p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
	p4 = 4;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	p0 = 2;
	p1 = 2;
	int t2[] = {0,2};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	int t3[] = {0,1};
			p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
	p4 = 7;
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	p0 = 3;
	p1 = 3;
	int t2[] = {0,3,3};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	int t3[] = {0,3,0};
			p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
	p4 = 15;
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	p0 = 3;
	p1 = 4;
	int t2[] = {0,3};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	int t3[] = {4,1};
			p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
	p4 = 11;
	all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	p0 = 5;
	p1 = 6;
	int t2[] = {0,4,2,5,0};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	int t3[] = {3,4,5,6,0};
			p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
	p4 = 48;
	all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	p0 = 557;
	p1 = 919;
	int t2[] = {81,509,428,6,448,149,77,142,40,405,109,247};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	int t3[] = {653,887,770,477,53,637,201,863,576,393,512,243};
			p3.assign(t3, t3 + sizeof(t3) / sizeof(t3[0]));
	p4 = 16255;
	all_right = KawigiEdit_RunTest(5, p0, p1, p2, p3, true, p4) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// You are a goblin miner.
// Your job is to mine gold.
// 
// Picture yourself located in a mine.
// The mine can be seen as a rectangular grid of (N+1) times (M+1) cells.
// Rows are numbered 0 through N, columns 0 through M.
// 
// You will work in the mine for several days.
// You can choose the cell where you will work today (on day 0).
// On each of the next days, you can either stay in the cell where you were on the previous day, or you can move to any other cell in the same row or in the same column.
// 
// Whenever somebody discovers gold in the mine, each goblin profits!
// Your profit is N + M, minus your Manhattan distance from the cell where the gold was discovered.
// Formally, if the gold is discovered at (a, b) and you are located at (c, d), your profit is N + M - |a-c| - |b-d|, where || denotes absolute value.
// 
// You are given the ints N and M.
// You are also given two vector <int>s: event_i and event_j.
// Both will contain the same number of elements.
// Assume that for each valid k, there will be exactly one gold discovery on day k: in the cell (event_i[k], event_j[k]).
// 
// Compute and return the maximum total profit you can get by correctly choosing the cells where you work on each day.
// 
// DEFINITION
// Class:MiningGoldEasy
// Method:GetMaximumGold
// Parameters:int, int, vector <int>, vector <int>
// Returns:int
// Method signature:int GetMaximumGold(int N, int M, vector <int> event_i, vector <int> event_j)
// 
// 
// CONSTRAINTS
// -N and M will be between 1 and 1,000,000, inclusive.
// -event_i will contain between 1 and 50 elements, inclusive.
// -event_j will contain the same number of elements as event_i.
// -The elements of event_i will range between 0 and N, inclusive.
// -The elements of event_j will range between 0 and M, inclusive.
// 
// 
// EXAMPLES
// 
// 0)
// 2
// 2
// {0}
// {0}
// 
// Returns: 4
// 
// Gold will be discovered today in the cell (0, 0). Your optimal strategy is to work there today.
// 
// 1)
// 2
// 2
// {0, 2}
// {0, 1}
// 
// Returns: 7
// 
// Gold will be discovered in the cell (0, 0) today and in the cell (2, 1) tomorrow.
// Note that you cannot move directly from (0, 0) to (2, 1), because these cells are neither in the same row nor in the same column.
// One optimal strategy is to work in the cell (0, 0) today and in the cell (2, 0) tomorrow.
// Your profit today will be 4, tomorrow it will be 3, thus the total profit is 4+3 = 7.
// 
// 2)
// 3
// 3
// {0, 3, 3}
// {0, 3, 0}
// 
// Returns: 15
// 
// 
// 
// 3)
// 3
// 4
// {0, 3}
// {4, 1}
// 
// Returns: 11
// 
// 
// 
// 4)
// 5
// 6
// {0, 4, 2, 5, 0}
// {3, 4, 5, 6, 0}
// 
// Returns: 48
// 
// 
// 
// 5)
// 557
// 919
// {81, 509, 428, 6, 448, 149, 77, 142, 40, 405, 109, 247}
// {653, 887, 770, 477, 53, 637, 201, 863, 576, 393, 512, 243}
// 
// Returns: 16255
// 
// 
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
