#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class WolvesAndSheep {
public:
	int getmin(vector <string> field) {
		
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	WolvesAndSheep *obj;
	int answer;
	obj = new WolvesAndSheep();
	clock_t startTime = clock();
	answer = obj->getmin(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	int p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"W.WSS","WW.S.",".SSS.","SSS.S",".SS.S"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 2;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {".....",".....","....."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {".SS","...","S..","W.W"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"WWWSWWSSWWW","WWSWW.SSWWW","WS.WSWWWWS."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 10;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {".W.S.W.W","W.W.S.W.",".S.S.W.W","S.S.S.W.",".S.W.W.S","S.S.W.W.",".W.W.W.S","W.W.S.S."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 7;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 5 -----
	string t0[] = {"W.SSWWSSSW.SS",".SSSSW.SSWWWW",".WWWWS.WSSWWS","SS.WSS..W.WWS","WSSS.SSWS.W.S","WSS.WS...WWWS","S.WW.S.SWWWSW","WSSSS.SSW...S","S.WWSW.WWSWSW",".WSSS.WWSWWWS","..SSSS.WWWSSS","SSWSWWS.W.SSW","S.WSWS..WSSS.","WS....W..WSS."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 24;
	all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 6 -----
	string t0[] = {"WW..SS","WW..SS","......","......","SS..WW","SS..WW"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 2;
	all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Farmer John has a huge rectangular pasture for his sheep.
// The pasture is divided into a grid of unit square cells.
// The sheep can travel freely between the cells.
// There is a wall around the pasture, so the sheep cannot leave it.
// One day, Farmer John found that wolves have infested the pasture through holes in the wall.
// Farmer John has fixed those holes, but the damage has been done: there are now some wolves in the pasture.
// More precisely, some cells of the pasture contain sheep, some contain wolves and some are empty.
// There are no cells that contain both sheep and wolves, and Farmer John would like to keep it that way.
// To make sure that the wolves cannot reach his sheep, Farmer John is going to build some fences.
// Each new fence has to be placed either between two rows or between two columns of cells.
// Each fence will start at one end of the pasture and reach all the way to the other end.
// Neither sheep nor wolves can cross the fences.
// The new fences must be placed in such a way that none of the wolves will be able to reach a sheep.
// You are given a vector <string> field.
// For each i and j, character j of element i of field represents the cell in row i, column j of the grid.
// (All indices in the previous sentence are 0-based.)
// Each character in field will be one of 'S' (a cell with sheep), 'W' (a cell with wolves), and '.' (an empty cell).
// Return the smallest number of new fences needed to separate the wolves from the sheep.
// 
// DEFINITION
// Class:WolvesAndSheep
// Method:getmin
// Parameters:vector <string>
// Returns:int
// Method signature:int getmin(vector <string> field)
// 
// 
// CONSTRAINTS
// -field will contain between 1 and 16 elements, inclusive.
// -Each element of field will contain between 1 and 16 characters, inclusive.
// -Each element of field will contain the same number of characters.
// -Each character of each element of field will be 'S', 'W' or '.'.
// 
// 
// EXAMPLES
// 
// 0)
// {"W.WSS",
//  "WW.S.",
//  ".SSS.",
//  "SSS.S",
//  ".SS.S"}
// 
// Returns: 2
// 
// The optimal solution is to build two fences: one between rows 1 and 2, the other between columns 2 and 3.
// (All those indices are 0-based.)
// This will divide the pasture into four smaller rectangles.
// One of those rectangles (the 2 by 3 rectangle in the top left corner) will contain only wolves, the other three will contain only sheep.
// 
// 1)
// {".....",
//  ".....",
//  "....."}
// 
// Returns: 0
// 
// There are no animals, thus we need no fences.
// 
// 2)
// {".SS",
//  "...",
//  "S..",
//  "W.W"}
// 
// Returns: 1
// 
// 
// 
// 3)
// {"WWWSWWSSWWW",
//  "WWSWW.SSWWW",
//  "WS.WSWWWWS."}
// 
// Returns: 10
// 
// 
// 
// 4)
// {".W.S.W.W",
//  "W.W.S.W.",
//  ".S.S.W.W",
//  "S.S.S.W.",
//  ".S.W.W.S",
//  "S.S.W.W.",
//  ".W.W.W.S",
//  "W.W.S.S."}
// 
// Returns: 7
// 
// 
// 
// 5)
// {"W.SSWWSSSW.SS",
//  ".SSSSW.SSWWWW",
//  ".WWWWS.WSSWWS",
//  "SS.WSS..W.WWS",
//  "WSSS.SSWS.W.S",
//  "WSS.WS...WWWS",
//  "S.WW.S.SWWWSW",
//  "WSSSS.SSW...S",
//  "S.WWSW.WWSWSW",
//  ".WSSS.WWSWWWS",
//  "..SSSS.WWWSSS",
//  "SSWSWWS.W.SSW",
//  "S.WSWS..WSSS.",
//  "WS....W..WSS."}
// 
// Returns: 24
// 
// 
// 
// 6)
// {"WW..SS",
//  "WW..SS",
//  "......",
//  "......",
//  "SS..WW",
//  "SS..WW"}
// 
// Returns: 2
// 
// 
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
