#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class LittleElephantAndIntervalsDiv2 {
public:
    map<string, bool> M;

	int getNumber(int M, vector <int> L, vector <int> R)
	{
	    int arr[M+1];
	    for(int i=0;i<=M;i++)
            arr[i]=0;
        for(int i=0;i<L.size();i++)
        {
            int a=L[i];
            int b=R[i];
            for(int j=a;j<=b;j++)
                arr[j]=i+1;
        }

        set<int> SS;
        for(int i=1;i<=M;i++)
        {
            if(arr[i])
            {
                //cout<<arr[i]<<" ";
                SS.insert(arr[i]);
            }
        }
        //cout<<endl;
        cout<<SS.size()<<endl;
        return 1<<SS.size();
    }
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, vector <int> p1, vector <int> p2, bool hasAnswer, int p3) {
	cout << "Test " << testNum << ": [" << p0 << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p1[i];
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p2.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p2[i];
	}
	cout << "}";
	cout << "]" << endl;
	LittleElephantAndIntervalsDiv2 *obj;
	int answer;
	obj = new LittleElephantAndIntervalsDiv2();
	clock_t startTime = clock();
	answer = obj->getNumber(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p3 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p3;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	int p0;
	vector <int> p1;
	vector <int> p2;
	int p3;

	{
	// ----- test 0 -----
	p0 = 4;
	int t1[] = {1,2,3};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {1,2,3};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 8;
	all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}

	{
	// ----- test 1 -----
	p0 = 3;
	int t1[] = {1,1,2};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {3,1,3};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 4;
	all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}

	{
	// ----- test 2 -----
	p0 = 100;
	int t1[] = {47};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {74};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 2;
	all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}

	{
	// ----- test 3 -----
	p0 = 100;
	int t1[] = {10,20,50};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {20,50,100};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 8;
	all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}

	{
	// ----- test 4 -----
	p0 = 42;
	int t1[] = {5,23,4,1,15,2,22,26,13,16};
			p1.assign(t1, t1 + sizeof(t1) / sizeof(t1[0]));
	int t2[] = {30,41,17,1,21,6,28,30,15,19};
			p2.assign(t2, t2 + sizeof(t2) / sizeof(t2[0]));
	p3 = 512;
	all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
	// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
//
// Little Elephant from the Zoo of Lviv has some balls arranged in a row. Each ball can be painted in one of two possible colors: black or white. Initially all the balls are painted white.
//
//
//
//
// You are given an int M, which represents the number of balls in the row.
// The balls are numbered from left to right, starting from 1.
// You are also given two vector <int>s L and R.
// To repaint balls, Little Elephant wants to use a robot.
// The robot will paint the balls in several consecutive stages.
// For each i, the i-th stage (1-based index) will look as follows:
// First, the robot will choose one of the two colors: white or black.
// Then, the robot will paint the balls with indices from L[i-1] to R[i-1], inclusive, using the chosen color.
// (Painting a ball covers all previous layers of paint.)
//
//
//
//
// Return the number of different colorings Little Elephant can get after the last stage. (Two colorings are considered different if there exists some ball that is white in one coloring and black in the other one).
//
//
// DEFINITION
// Class:LittleElephantAndIntervalsDiv2
// Method:getNumber
// Parameters:int, vector <int>, vector <int>
// Returns:int
// Method signature:int getNumber(int M, vector <int> L, vector <int> R)
//
//
// CONSTRAINTS
// -M will be between 1 and 100, inclusive.
// -L will contain between 1 and 10 elements, inclusive.
// -R will contain the same number of elements as L.
// -Each element of R will be between 1 and M, inclusive.
// -i-th element of L will be between 1 and R[i], inclusive.
//
//
// EXAMPLES
//
// 0)
// 4
// {1, 2, 3}
// {1, 2, 3}
//
// Returns: 8
//
// In the three stages the robot will choose the color for balls number 1, 2, and 3. The choices are independent of each other. The last, fourth ball will always remain white. Thus there are 2*2*2 = 8 different colorings.
//
// 1)
// 3
// {1, 1, 2}
// {3, 1, 3}
//
// Returns: 4
//
// In the first stage the robot colors all three balls. The color chosen for the first stage does not matter, because in the second stage the robot will repaint ball 1, and in the third stage it will repaint balls 2 and 3.
//
// 2)
// 100
// {47}
// {74}
//
// Returns: 2
//
//
//
// 3)
// 100
// {10, 20, 50}
// {20, 50, 100}
//
// Returns: 8
//
//
//
// 4)
// 42
// {5, 23, 4, 1, 15, 2, 22, 26, 13, 16}
// {30, 41, 17, 1, 21, 6, 28, 30, 15, 19}
//
// Returns: 512
//
//
//
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
