#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

class FoxAndGomoku {
public:
    string win(vector <string> board)
	{
	    for(int i=0;i<board.size();i++)
        {
            for(int j=0;j<board[i].length();j++)
            {
                if(board[i][j]=='o')
                {
                    int ans=0, temp=0;
                    for(int k=j;k<board[i].length();k++)
                        if(board[i][k]=='o') temp++;
                        else break;
                    ans = max(ans, temp);
                    temp=0;
                    for(int k=i;k<board.size();k++)
                        if(board[k][j]=='o') temp++;
                        else break;
                    ans = max(ans,temp);
                    temp=0;
                    for(int k=i, l=j;k<board.size();k++, l--)
                        if(board[k][l]=='o') temp++;
                        else break;
                    ans = max(ans,temp);
                    temp=0;
                    for(int k=i, l=j;k<board.size();k++, l++)
                        if(board[k][l]=='o') temp++;
                        else break;
                    ans = max(ans,temp);
                    //cout<<ans<<endl;
                    if(ans>=5) return "found";
                }
            }
        }
        return "not found";

	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, string p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	FoxAndGomoku *obj;
	string answer;
	obj = new FoxAndGomoku();
	clock_t startTime = clock();
	answer = obj->win(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "\"" << p1 << "\"" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "\"" << answer << "\"" << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	vector <string> p0;
	string p1;

	{
	// ----- test 0 -----
	string t0[] = {"....o.","...o..","..o...",".o....","o.....","......"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "found";
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 1 -----
	string t0[] = {"oooo.",".oooo","oooo.",".oooo","....."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "not found";
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 2 -----
	string t0[] = {"oooo.",".oooo","oooo.",".oooo","....o"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "found";
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 3 -----
	string t0[] = {"o.....",".o....","..o...","...o..","....o.","......"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "found";
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 4 -----
	string t0[] = {"o....","o.o..","o.o.o","o.o..","o...."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "found";
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 5 -----
	string t0[] = {"..........","..........","..oooooo..","..o.......","..o.......","..oooooo..",".......o..",".......o..","..oooooo..",".........."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "found";
	all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 6 -----
	string t0[] = {"..........","..........","..oooo.o..","..o.......","..o.......","..o.oooo..",".......o..",".......o..","..oooo.o..",".........."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "not found";
	all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 7 -----
	string t0[] = {"ooooo","ooooo","ooooo","ooooo","ooooo"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "found";
	all_right = KawigiEdit_RunTest(7, p0, true, p1) && all_right;
	// ------------------
	}

	{
	// ----- test 8 -----
	string t0[] = {".....",".....",".....",".....","....."};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = "not found";
	all_right = KawigiEdit_RunTest(8, p0, true, p1) && all_right;
	// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Fox Ciel is going to play Gomoku with her friend Fox Jiro.
// Ciel plays better, so before they start she allowed Jiro to put some of his pieces on the board.
//
//
// You are given a vector <string> board that represents a square board.
// The character board[i][j] represents the cell with coordinates (i,j).
// Each of those characters is either '.' (representing an empty cell) or 'o' (representing a cell with Jiro's piece).
//
//
// Of course, Ciel does not want Jiro to win the game before she has a chance to play.
// Thus she now has to check the board and determine whether there are five consecutive tokens somewhere on the board.
//
//
// Determine whether there are 5 consecutive cells (horizontally, vertically, or diagonally) that contain Jiro's tokens.
// Return "found" (quotes for clarity) if there are five such cells anywhere on the board.
// Otherwise, return "not found".
//
// DEFINITION
// Class:FoxAndGomoku
// Method:win
// Parameters:vector <string>
// Returns:string
// Method signature:string win(vector <string> board)
//
//
// CONSTRAINTS
// -n will be between 5 and 15, inclusive.
// -board will contain exactly n elements.
// -Each element in board will contain exactly n characters.
// -Each character in board will be 'o' or '.'.
//
//
// EXAMPLES
//
// 0)
// {"....o.",
//  "...o..",
//  "..o...",
//  ".o....",
//  "o.....",
//  "......"}
//
// Returns: "found"
//
// There is five continue pieces diagonally.
//
// 1)
// {"oooo.",
//  ".oooo",
//  "oooo.",
//  ".oooo",
//  "....."}
//
//
// Returns: "not found"
//
// There is no five-in-a-row on this board.
//
// 2)
// {"oooo.",
//  ".oooo",
//  "oooo.",
//  ".oooo",
//  "....o"}
//
//
// Returns: "found"
//
// Five consecutive tokens can be found in the following cells: (0,0), (1,1), (2,2), (3,3), and (4,4).
//
// 3)
// {"o.....",
//  ".o....",
//  "..o...",
//  "...o..",
//  "....o.",
//  "......"}
//
// Returns: "found"
//
//
//
// 4)
// {"o....",
//  "o.o..",
//  "o.o.o",
//  "o.o..",
//  "o...."}
//
// Returns: "found"
//
//
//
// 5)
// {"..........",
//  "..........",
//  "..oooooo..",
//  "..o.......",
//  "..o.......",
//  "..oooooo..",
//  ".......o..",
//  ".......o..",
//  "..oooooo..",
//  ".........."}
//
//
//
// Returns: "found"
//
//
//
// 6)
// {"..........",
//  "..........",
//  "..oooo.o..",
//  "..o.......",
//  "..o.......",
//  "..o.oooo..",
//  ".......o..",
//  ".......o..",
//  "..oooo.o..",
//  ".........."}
//
//
// Returns: "not found"
//
//
//
// 7)
// {"ooooo",
//  "ooooo",
//  "ooooo",
//  "ooooo",
//  "ooooo"}
//
// Returns: "found"
//
//
//
// 8)
// {".....",
//  ".....",
//  ".....",
//  ".....",
//  "....."}
//
// Returns: "not found"
//
//
//
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
