#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

#define INF (1<<30)
int FinalValue;
map<int, bool> M;

int revers(int a)
{
    stringstream ss;
    ss.clear();
    ss<<a;
    string s="";
    ss>>s;

    reverse(s.begin(), s.end());
    ss.clear();
    ss<<s;
    ss>>a;
    return a;

}
int rec(int a)
{
    if(a<=0) return INF;
    if(a==FinalValue)
    {
        return 0;
    }
    int ret;
    ret =  1 + rec(a/10);
    if(M[a]==false)
    {
        M[a]=true;
        ret = min(ret, 1+rec(revers(a)));

    }

    return ret;
}

class TheNumberGame {
public:
	string determineOutcome(int A, int B)
	{
        FinalValue = B;
        M.clear();
	    int ans = rec(A);
	    if(ans>=INF)
            return "Manao loses";
        return "Manao wins";
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
#include <iostream>
#include <string>
#include <vector>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, int p1, bool hasAnswer, string p2) {
	cout << "Test " << testNum << ": [" << p0 << "," << p1;
	cout << "]" << endl;
	TheNumberGame *obj;
	string answer;
	obj = new TheNumberGame();
	clock_t startTime = clock();
	answer = obj->determineOutcome(p0, p1);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << "\"" << p2 << "\"" << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << "\"" << answer << "\"" << endl;
	if (hasAnswer) {
		res = answer == p2;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;

	int p0;
	int p1;
	string p2;

	{
	// ----- test 0 -----
	p0 = 45;
	p1 = 4;
	p2 = "Manao wins";
	all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 1 -----
	p0 = 45;
	p1 = 5;
	p2 = "Manao wins";
	all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 2 -----
	p0 = 99;
	p1 = 123;
	p2 = "Manao loses";
	all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
	// ------------------
	}

	{
	// ----- test 3 -----
	p0 = 2356236;
	p1 = 5666;
	p2 = "Manao loses";
	all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
	// ------------------
	}

	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// Manao has recently invented a brand new game called The Number Game. He usually plays this game against his friend.
//
// Initially, Manao has an integer A and his friend has an integer B. Note that neither A nor B contain a zero digit in their base 10 representation. The players make moves alternatively with Manao starting first. In each move, the player can either reverse his current number, or he can divide it by 10 (using integer division).
// For example, if the current number is 12849, the player can either reverse it to obtain 94821, or he can divide it by 10 to obtain 1284.
// Note that we always round down when using integer division.
// Also note that each player is only allowed to change his own number, and not the number of the other player.
//
// If after some move the players' numbers become equal, Manao is declared the winner. If after 1000 moves (that is, 500 moves by Manao and 500 by his friend) Manao has not won, he loses. Given A and B, determine whether Manao would win if both players play optimally. Return "Manao wins" or "Manao loses" accordingly.
//
// DEFINITION
// Class:TheNumberGame
// Method:determineOutcome
// Parameters:int, int
// Returns:string
// Method signature:string determineOutcome(int A, int B)
//
//
// CONSTRAINTS
// -A will be between 1 and 999,999,999, inclusive.
// -B will be between 1 and 999,999,999, inclusive.
// -A and B will not contain a zero digit in base 10 representation.
// -A and B will be distinct.
//
//
// EXAMPLES
//
// 0)
// 45
// 4
//
// Returns: "Manao wins"
//
// Manao can win in one move by dividing his number by 10.
//
// 1)
// 45
// 5
//
// Returns: "Manao wins"
//
// There are several possible scenarios this game can follow:
//
// Manao divides by 10 and obtains 4. Now his opponent can reverse his number and obtain 5 again. Obviously, no matter what Manao does in his next 499 moves, his opponent can evade him.
// Manao reverses his number and obtains 54. His opponent reverses his 5. Manao divides 54 by 10 and obtains 5, thus making the numbers equal
// Manao reverses his number and obtains 54. His opponent divides by 10 and obtains zero. Manao will win in three moves, dividing his number by 10 twice.
//
// Obviously, Manao will not choose to divide by 10 in his first move and will win.
//
// 2)
// 99
// 123
//
// Returns: "Manao loses"
//
// No matter how Manao plays, the opponent can perform reverse moves until the end of the game.
//
// 3)
// 2356236
// 5666
//
// Returns: "Manao loses"
//
//
//
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
